---
format:
  # Core behavior
  disable: false
  line_width: 100
  line_ending: unix

  # Indentation
  tab_size: 2
  use_tabchars: false

  # Spacing around command/control names
  separate_ctrl_name_with_space: false
  separate_fn_name_with_space: false

  # Parentheses handling
  dangle_parens: false
  dangle_align: prefix
  min_prefix_chars: 4
  max_prefix_chars: 10

  # Horizontal wrapping limits
  max_subgroups_hwrap: 2
  max_rows_cmdline: 2
  max_pargs_hwrap: 4 # slightly tighter wrap for long arg lists
  max_lines_hwrap: 3 # allow one more continuation line

  # Keyword and command casing
  command_case: lower
  keyword_case: upper

  # Sorting (keep stable; don't reorder author-provided lists)
  enable_sort: true # Only used where explicit sort rules apply
  autosort: false # Never auto-sort set()/list() args etc.

  # Enforce consistent wrapping on long, noisy commands.
  always_wrap:
    - add_custom_command
    - add_custom_target
    - target_link_libraries
    - target_include_directories
    - target_compile_definitions
    - target_sources

markup:
  # Keep docstring-style markup disabled to avoid surprises in comments.
  enable_markup: false
