---
format:
  disable: false
  line_width: 100
  tab_size: 2
  use_tabchars: false
  separate_ctrl_name_with_space: false
  separate_fn_name_with_space: false
  dangle_parens: false
  dangle_align: prefix
  min_prefix_chars: 4
  max_prefix_chars: 10
  max_subgroups_hwrap: 2
  max_pargs_hwrap: 6
  max_rows_cmdline: 2
  max_lines_hwrap: 2
  line_ending: unix
  command_case: lower
  keyword_case: upper
  enable_sort: true
  autosort: false

markup:
  enable_markup: false
