---
# ============================================================================
# Byteweave Prettier configuration
# - YAML-only; stable formatting across CI
# - No comment/prose reflow
# - yamllint-friendly (no inline comments; if used, pad with two spaces)
# ============================================================================

printWidth: 100
tabWidth: 2
useTabs: false
endOfLine: lf

# Do not wrap prose/comments (mostly affects Markdown; harmless for YAML)
proseWrap: preserve

# Avoid formatting embedded languages in fenced blocks
embeddedLanguageFormatting: off

# Apply options only to YAML files
overrides:
  - files:
      - "*.yml"
      - "*.yaml"
    options: {}
